# Generated by Django 5.1.6 on 2025-03-01 17:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClubInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general', models.TextField(help_text='The general message.')),
                ('vision1', models.TextField(help_text='The vision of the club.')),
                ('vision2', models.TextField(help_text='The vision of the club.')),
                ('mission1', models.TextField(help_text='The mission of the club.')),
                ('mission2', models.TextField(help_text='The mission of the club.')),
                ('goals1', models.TextField(help_text='The goals of the club.')),
                ('goals2', models.TextField(help_text='The goals of the club.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the information was last updated.')),
            ],
            options={
                'verbose_name': 'Club Information',
                'verbose_name_plural': 'Club Information',
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='The email address of the club.', max_length=254)),
                ('phone_number', models.CharField(help_text='The phone number of the club.', max_length=20)),
                ('address', models.TextField(help_text='The physical address of the club.')),
                ('website', models.URLField(blank=True, help_text='The website URL of the club.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the contact information was last updated.')),
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contact Information',
            },
        ),
        migrations.CreateModel(
            name='RegisterStartups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startup_name', models.CharField(max_length=255, verbose_name='Startup Name')),
                ('description', models.TextField(help_text='Brief description of the startup', verbose_name='Description')),
                ('website', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Website')),
                ('founder_name', models.CharField(max_length=255, verbose_name='Founder Name')),
                ('founder_email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Founder Email')),
                ('founder_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Founder Phone')),
                ('college_department', models.CharField(blank=True, max_length=255, null=True, verbose_name='Department')),
                ('college_year', models.CharField(blank=True, choices=[('FE', 'First Year (FE)'), ('SE', 'Second Year (SE)'), ('TE', 'Third Year (TE)'), ('BE', 'Final Year (BE)')], max_length=2, null=True, verbose_name='College Year')),
                ('registration_date', models.DateField(auto_now_add=True, verbose_name='Registration Date')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Approved')),
                ('linkedin_url', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()], verbose_name='LinkedIn URL')),
                ('instagram_url', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Instagram URL')),
                ('twitter_url', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Twitter URL')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Registered Startup',
                'verbose_name_plural': 'Registered Startups',
            },
        ),
    ]
