# Generated by Django 5.1.6 on 2025-02-26 11:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClubInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general', models.TextField(help_text='The general message.')),
                ('vision', models.TextField(help_text='The vision of the club.')),
                ('mission', models.TextField(help_text='The mission of the club.')),
                ('goals', models.TextField(help_text='The goals of the club.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the information was last updated.')),
            ],
            options={
                'verbose_name': 'Club Information',
                'verbose_name_plural': 'Club Information',
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='The email address of the club.', max_length=254)),
                ('phone_number', models.CharField(help_text='The phone number of the club.', max_length=20)),
                ('address', models.TextField(help_text='The physical address of the club.')),
                ('website', models.URLField(blank=True, help_text='The website URL of the club.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the contact information was last updated.')),
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contact Information',
            },
        ),
        migrations.CreateModel(
            name='RegisterStartups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startup_name', models.CharField(max_length=255, verbose_name='Startup Name')),
                ('description', models.TextField(help_text='Brief description of the startup', verbose_name='Description')),
                ('website', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Website')),
                ('founder_name', models.CharField(max_length=255, verbose_name='Founder Name')),
                ('founder_email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Founder Email')),
                ('founder_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Founder Phone')),
                ('college_department', models.CharField(blank=True, max_length=255, null=True, verbose_name='Department')),
                ('college_year', models.CharField(blank=True, choices=[('FE', 'First Year (FE)'), ('SE', 'Second Year (SE)'), ('TE', 'Third Year (TE)'), ('BE', 'Final Year (BE)')], max_length=2, null=True, verbose_name='College Year')),
                ('registration_date', models.DateField(auto_now_add=True, verbose_name='Registration Date')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Approved')),
                ('linkedin_url', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()], verbose_name='LinkedIn URL')),
                ('instagram_url', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Instagram URL')),
                ('twitter_url', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Twitter URL')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Registered Startup',
                'verbose_name_plural': 'Registered Startups',
            },
        ),
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('github', 'GitHub'), ('website', 'Website')], help_text='The social media platform.', max_length=20)),
                ('url', models.URLField(help_text='The URL of the social media profile or page.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the link was added.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the link was last updated.')),
            ],
            options={
                'verbose_name': 'Social Media Link',
                'verbose_name_plural': 'Social Media Links',
            },
        ),
    ]
