# Generated by Django 5.1.6 on 2025-02-26 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GeneralApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialMediaLink',
        ),
    ]
