# Generated by Django 5.1.6 on 2025-03-01 20:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeneralApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HyperLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('info', models.CharField(max_length=150)),
                ('link', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
            ],
        ),
    ]
