# Generated by Django 5.1.6 on 2025-02-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeneralApp', '0002_delete_socialmedialink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clubinfo',
            old_name='goals',
            new_name='goals1',
        ),
        migrations.RenameField(
            model_name='clubinfo',
            old_name='mission',
            new_name='mission1',
        ),
        migrations.RenameField(
            model_name='clubinfo',
            old_name='vision',
            new_name='vision1',
        ),
        migrations.AddField(
            model_name='clubinfo',
            name='goals2',
            field=models.TextField(default='', help_text='The goals of the club.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clubinfo',
            name='mission2',
            field=models.TextField(default='', help_text='The mission of the club.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clubinfo',
            name='vision2',
            field=models.TextField(default='', help_text='The vision of the club.'),
            preserve_default=False,
        ),
    ]
