# Generated by Django 5.1.6 on 2025-03-01 20:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeneralApp', '0002_hyperlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubinfo',
            name='link',
            field=models.URLField(blank=True, help_text='Team register link', null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
