# Generated by Django 5.1.6 on 2025-03-01 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeneralApp', '0003_clubinfo_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegisterStartups',
        ),
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name': 'Registered Startup', 'verbose_name_plural': 'Registered Startups'},
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
