# Generated by Django 5.1.6 on 2025-03-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeneralApp', '0004_delete_registerstartups_alter_contactinfo_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubinfo',
            name='general',
        ),
        migrations.RemoveField(
            model_name='clubinfo',
            name='goals1',
        ),
        migrations.RemoveField(
            model_name='clubinfo',
            name='goals2',
        ),
        migrations.RemoveField(
            model_name='clubinfo',
            name='mission1',
        ),
        migrations.RemoveField(
            model_name='clubinfo',
            name='mission2',
        ),
        migrations.RemoveField(
            model_name='clubinfo',
            name='vision1',
        ),
        migrations.RemoveField(
            model_name='clubinfo',
            name='vision2',
        ),
        migrations.AddField(
            model_name='clubinfo',
            name='main_img',
            field=models.ImageField(default='', upload_to='header_img/'),
            preserve_default=False,
        ),
    ]
