# Generated by Django 5.1.6 on 2025-03-28 09:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeneralApp', '0005_remove_clubinfo_general_remove_clubinfo_goals1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubinfo',
            name='img_link',
            field=models.URLField(blank=True, help_text='Image link', null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
