# Generated by Django 5.1.6 on 2025-03-28 16:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeneralApp', '0006_clubinfo_img_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubinfo',
            name='img_link',
            field=models.URLField(blank=True, help_text='Image redirecting link', null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
