# Generated by Django 5.1.6 on 2025-03-28 18:14

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeneralApp', '0007_alter_clubinfo_img_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='achivement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('header_image', models.ImageField(upload_to='event_headers/')),
                ('detail_description', tinymce.models.HTMLField(blank=True)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, default='', help_text='Enter 10 words description only', max_length=450)),
                ('slug', models.SlugField(blank=True, help_text='keep empty', unique=True)),
            ],
        ),
    ]
