# Generated by Django 5.1.6 on 2025-02-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentTeam', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='pastEvent',
        ),
        migrations.AddField(
            model_name='event',
            name='link',
            field=models.URLField(blank=True, help_text='Add event link (only for upcoming and ongoing events)', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='upcoming', max_length=20),
        ),
    ]
