# Generated by Django 5.1.6 on 2025-03-28 09:08

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentTeam', '0001_initial'),
        ('pcrTeam', '0002_remove_event_imgbanner_event_header_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventInformations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Determines the display order')),
                ('text', tinymce.models.HTMLField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_texts', to='pcrTeam.event')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
