# Generated by Django 5.1.6 on 2025-02-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentTeam', '0002_remove_event_pastevent_event_link_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Detail_description',
            field=models.TextField(blank=True, default='', max_length=450),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Enter 10 words description only', max_length=450),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, help_text='keep empty', unique=True),
        ),
    ]
