# Generated by Django 5.1.6 on 2025-02-27 16:27

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentTeam', '0003_event_detail_description_alter_event_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Detail_description',
            field=tinymce.models.HTMLField(),
        ),
    ]
