# Generated by Django 5.1.6 on 2025-02-27 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentTeam', '0004_alter_event_detail_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='Detail_description',
            new_name='detail_description',
        ),
    ]
