# Generated by Django 5.1.6 on 2025-02-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentTeam', '0005_rename_detail_description_event_detail_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.CharField(default='', help_text='Seprate the tag with comma', max_length=150),
            preserve_default=False,
        ),
    ]
