# Generated by Django 5.1.6 on 2025-03-01 20:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technicalTeam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterStartups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startup_name', models.CharField(max_length=255, verbose_name='Startup Name')),
                ('description', models.TextField(help_text='Brief description of the startup', verbose_name='Description')),
                ('website', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Website')),
                ('founder_name', models.CharField(max_length=255, verbose_name='Founder Name')),
                ('founder_email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Founder Email')),
                ('founder_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Founder Phone')),
                ('college_department', models.CharField(blank=True, max_length=255, null=True, verbose_name='Department')),
                ('college_year', models.CharField(blank=True, choices=[('FE', 'First Year (FE)'), ('SE', 'Second Year (SE)'), ('TE', 'Third Year (TE)'), ('BE', 'Final Year (BE)')], max_length=2, null=True, verbose_name='College Year')),
                ('registration_date', models.DateField(auto_now_add=True, verbose_name='Registration Date')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Approved')),
                ('linkedin_url', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()], verbose_name='LinkedIn URL')),
                ('instagram_url', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Instagram URL')),
                ('twitter_url', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Twitter URL')),
            ],
        ),
    ]
