# Generated by Django 5.1.6 on 2025-02-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technicalTeam', '0002_alter_customuser_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('designation', models.CharField(max_length=250)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='faculty_photos/', verbose_name='Profile Photo')),
            ],
        ),
    ]
