# Generated by Django 5.1.6 on 2025-02-26 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technicalTeam', '0003_faculty'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='faculty',
            new_name='FacultyMember',
        ),
    ]
