# Generated by Django 5.1.6 on 2025-03-01 17:31

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pcrTeam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('github', 'GitHub'), ('website', 'Website')], help_text='The social media platform.', max_length=20)),
                ('url', models.URLField(help_text='The URL of the social media profile or page.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the link was added.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the link was last updated.')),
            ],
            options={
                'verbose_name': 'Social Media Link',
                'verbose_name_plural': 'Social Media Links',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('hero_Image', models.ImageField(upload_to='event_images')),
                ('events', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcrTeam.event', verbose_name='content_event')),
            ],
        ),
        migrations.CreateModel(
            name='SectionContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('sticky', 'Sticky')], max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='mediaTeam.event')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MediaContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('text', 'Text')], max_length=10)),
                ('aspect_ratio', models.CharField(blank=True, choices=[('16/9', '16:9'), ('3/4', '3:4'), ('8/9', '8:9')], max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('position', models.CharField(blank=True, help_text="For double sections: 'left' or 'right'", max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Event-Images/')),
                ('image_alt', models.CharField(blank=True, max_length=255)),
                ('video', models.FileField(blank=True, null=True, upload_to='Event-Videos/')),
                ('video_poster', models.ImageField(blank=True, null=True, upload_to='Event-Video-Posters/')),
                ('info', tinymce.models.HTMLField(blank=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='mediaTeam.sectioncontent')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
