# Generated by Django 5.1.6 on 2025-03-01 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaTeam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='hero_Image',
            field=models.ImageField(upload_to='event_images/hero/'),
        ),
        migrations.AlterField(
            model_name='sectioncontent',
            name='section_type',
            field=models.CharField(choices=[('single', 'Single (One Image only)'), ('double', 'Double (Two Image Side by Side)'), ('sticky', 'Sticky (Image and Text Side by Side)')], max_length=10),
        ),
    ]
