# Generated by Django 5.1.6 on 2025-02-27 21:00

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentTeam', '0006_event_tags'),
        ('mediaTeam', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectioncontent',
            name='EventImage_content',
        ),
        migrations.RemoveField(
            model_name='videocontent',
            name='section',
        ),
        migrations.AlterModelOptions(
            name='eventimage',
            options={},
        ),
        migrations.RemoveField(
            model_name='eventimage',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='eventimage',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='eventimage',
            name='title',
        ),
        migrations.RemoveField(
            model_name='eventimage',
            name='updated_date',
        ),
        migrations.AddField(
            model_name='eventimage',
            name='hero_Image',
            field=models.ImageField(default='', upload_to='event_images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mediacontent',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='Event-Videos/'),
        ),
        migrations.AddField(
            model_name='mediacontent',
            name='video_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mediacontent',
            name='video_poster',
            field=models.ImageField(blank=True, null=True, upload_to='Event-Video-Posters/'),
        ),
        migrations.AddField(
            model_name='sectioncontent',
            name='event_image',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='mediaTeam.eventimage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventimage',
            name='description',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='mediacontent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Event-Images/'),
        ),
        migrations.AlterField(
            model_name='mediacontent',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('text', 'Text')], max_length=10),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentTeam.event', verbose_name='content_event')),
            ],
        ),
        migrations.AlterField(
            model_name='eventimage',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mediaTeam.event'),
        ),
        migrations.DeleteModel(
            name='EventImageContent',
        ),
        migrations.DeleteModel(
            name='VideoContent',
        ),
    ]
