# Generated by Django 5.1.6 on 2025-02-27 21:11

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaTeam', '0002_remove_sectioncontent_eventimage_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectioncontent',
            name='event_image',
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='hero_Image',
            field=models.ImageField(default='', upload_to='event_images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sectioncontent',
            name='event',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='mediaTeam.event'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='EventImage',
        ),
    ]
