# Generated by Django 5.1.6 on 2025-03-28 08:51

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaTeam', '0002_alter_event_hero_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectioncontent',
            name='event',
        ),
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='events',
        ),
        migrations.RemoveField(
            model_name='event',
            name='hero_Image',
        ),
        migrations.AddField(
            model_name='event',
            name='detail_description',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='header_image',
            field=models.ImageField(default='', upload_to='event_headers/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Determines the display order')),
                ('image', models.ImageField(upload_to='event_images/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_images', to='mediaTeam.event')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EventText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Determines the display order')),
                ('text', tinymce.models.HTMLField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_texts', to='mediaTeam.event')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='MediaContent',
        ),
        migrations.DeleteModel(
            name='SectionContent',
        ),
    ]
