# Generated by Django 5.1.6 on 2025-02-27 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediaTeam', '0003_remove_sectioncontent_event_image_event_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
    ]
