# Generated by Django 5.1.6 on 2025-03-28 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaTeam', '0003_remove_sectioncontent_event_remove_event_date_and_more'),
        ('pcrTeam', '0002_remove_event_imgbanner_event_header_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventimage',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_images', to='pcrTeam.event'),
        ),
        migrations.AlterField(
            model_name='eventtext',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_texts', to='pcrTeam.event'),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
