# Generated by Django 5.1.6 on 2025-03-28 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediaTeam', '0004_alter_eventimage_event_alter_eventtext_event_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventText',
        ),
    ]
