# Generated by Django 5.1.6 on 2025-02-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaTeam', '0004_remove_event_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediacontent',
            old_name='text_content',
            new_name='info',
        ),
        migrations.RemoveField(
            model_name='mediacontent',
            name='video_description',
        ),
        migrations.AddField(
            model_name='mediacontent',
            name='infoimage',
            field=models.ImageField(blank=True, null=True, upload_to='Event-Images/'),
        ),
    ]
