# Generated by Django 5.1.6 on 2025-03-28 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaTeam', '0005_delete_eventtext'),
        ('pcrTeam', '0002_remove_event_imgbanner_event_header_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventimage',
            options={},
        ),
        migrations.RemoveField(
            model_name='eventimage',
            name='order',
        ),
        migrations.CreateModel(
            name='EventVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_url', models.URLField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_videos', to='pcrTeam.event')),
            ],
        ),
    ]
