# Generated by Django 5.1.6 on 2025-02-27 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediaTeam', '0005_rename_text_content_mediacontent_info_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediacontent',
            old_name='infoimage',
            new_name='info_Image',
        ),
    ]
