# Generated by Django 5.1.6 on 2025-03-28 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeneralApp', '0008_achivement'),
        ('mediaTeam', '0006_alter_eventimage_options_remove_eventimage_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchivementImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='event_images/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_images', to='GeneralApp.achivement')),
            ],
        ),
        migrations.CreateModel(
            name='AchivementVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_url', models.URLField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_videos', to='GeneralApp.achivement')),
            ],
        ),
    ]
