# Generated by Django 5.1.6 on 2025-02-27 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaTeam', '0006_rename_infoimage_mediacontent_info_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediacontent',
            name='info_Image',
        ),
        migrations.AlterField(
            model_name='mediacontent',
            name='aspect_ratio',
            field=models.CharField(blank=True, choices=[('16/9', '16:9'), ('8/9', '8:9')], max_length=10),
        ),
    ]
