# Generated by Django 5.1.6 on 2025-02-27 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaTeam', '0007_remove_mediacontent_info_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediacontent',
            name='aspect_ratio',
            field=models.CharField(blank=True, choices=[('16/9', '16:9'), ('8/9', '08:9')], max_length=10),
        ),
    ]
