# Generated by Django 5.1.6 on 2025-02-27 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaTeam', '0009_alter_mediacontent_aspect_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediacontent',
            name='aspect_ratio',
            field=models.CharField(blank=True, choices=[('16/9', '16:9'), ('3/4', '3:4'), ('8/9', '8:9')], max_length=10),
        ),
    ]
